[[people]]
name = "Deon"
photo = "./assets/deon.webp"
quote = "Deon is the incredibly devoted teacher behind Oats Robotics. He has been with the club since its beginning in 2009 and none of this would have been possible without him. He gives up his free time every Saturday to run the club as a volunteer - showing so much dedication to supporting us."

[[people]]
name = "Fritha ..."
photo = "./assets/fritha.webp"
quote = "Fritha is the club's manager, who does all the admin and organization. She arranges tournaments, manages paperwork, and coordinates with the school. Without Fritha, things would quickly fall apart."

[[people]]
name = "Brian ..."
photo = "./assets/brian.webp"
quote = "Brian provides technical support, manages the club’s parts and resources, drives us to tournaments, and supports us while we are there. Without him we wouldn’t have been able to get to nationals to compete!"
