[[people]]
name = "Tom"
photo = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F004%2F511%2F281%2Foriginal%2Fdefault-avatar-photo-placeholder-profile-picture-vector.jpg&f=1&nofb=1&ipt=3d3fe1367451c731ca2683bef52453d2991e78332c2e455a06a89e1270c25a77"
quote = "hi blah blah blah I really like worlds"

[[people]]
name = "Indie"
photo = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F004%2F511%2F281%2Foriginal%2Fdefault-avatar-photo-placeholder-profile-picture-vector.jpg&f=1&nofb=1&ipt=3d3fe1367451c731ca2683bef52453d2991e78332c2e455a06a89e1270c25a77"
quote = "hi blah blah blah I really like worlds"

[[people]]
name = "Finn"
photo = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F004%2F511%2F281%2Foriginal%2Fdefault-avatar-photo-placeholder-profile-picture-vector.jpg&f=1&nofb=1&ipt=3d3fe1367451c731ca2683bef52453d2991e78332c2e455a06a89e1270c25a77"
quote = "hi blah blah blah I really like worlds"

[[people]]
name = "Rosa"
photo = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F004%2F511%2F281%2Foriginal%2Fdefault-avatar-photo-placeholder-profile-picture-vector.jpg&f=1&nofb=1&ipt=3d3fe1367451c731ca2683bef52453d2991e78332c2e455a06a89e1270c25a77"
quote = "hi blah blah blah I really like worlds"

[[people]]
name = "William"
photo = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F004%2F511%2F281%2Foriginal%2Fdefault-avatar-photo-placeholder-profile-picture-vector.jpg&f=1&nofb=1&ipt=3d3fe1367451c731ca2683bef52453d2991e78332c2e455a06a89e1270c25a77"
quote = "hi blah blah blah I really like worlds"
