name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # setup nix
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: false
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checks
        run: |
          nix flake check --show-trace

      - name: Build
        run: |
          nix build

      # deploy
      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./result"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4
